services:
  db:
    image: postgres:15
    container_name: taskmanager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: task-managger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: taskmanager-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: taskmanager-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: farkaszalan2001@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pgdata:
  redisdata:

networks:
  backend:
    driver: bridge
